UKHomeOffice/firearms

- apps/new-dealer/acceptance/features/handle.js
- apps/new-dealer/acceptance/pages/handle.js
- apps/new-dealer/fields/index.js
- apps/new-dealer/index.js
- apps/new-dealer/translations/src/en/fields.json
- apps/new-dealer/translations/src/en/validation.json
Changes have been made to the step based on @joefitter's changes to the checkboxes on the passport template mixins
* In the route config, the field has changed from 2 fields to 1.
* In the fields config, 2 checkbox fields have changed to 1 checkbox group.
* The field translations have changed based on the checkbox group change.
> Relates to flho-145 Handle step

- apps/new-dealer/acceptance/features/first-authority-holders-name.js
- apps/new-dealer/acceptance/features/second-authority-holders-name.js
- apps/new-dealer/acceptance/pages/first-authority-holders-birth.js
- apps/new-dealer/acceptance/pages/first-authority-holders-name.js
- apps/new-dealer/acceptance/pages/second-authority-holders-birth.js
- apps/new-dealer/acceptance/pages/second-authority-holders-name.js
- apps/new-dealer/fields/index.js
- apps/new-dealer/index.js
- apps/new-dealer/translations/src/en/fields.json
- apps/new-dealer/translations/src/en/pages.json
- apps/new-dealer/translations/src/en/validation.json
- codecept.conf.js
This PR has the steps for authority holders name. This has been broken up into two steps: first-authority-holders name and second-authority-holders-name. The latter only occurs when 'two' is selected on the authority-holders step.
* Added steps to route config,
* Added fields to fields config,
* Added translations for pages, fields and validation,
* Added acceptance tests for both the steps,
* Added page helpers for the tests
> flho-170 Authority holders name step.

- apps/new-dealer/acceptance/features/contact-address-authority-holder.js
- apps/new-dealer/acceptance/features/contact-details.js
- apps/new-dealer/acceptance/pages/contact-address-authority-holder.js
- apps/new-dealer/acceptance/pages/contact-address.js
- apps/new-dealer/acceptance/pages/summary.js
- apps/new-dealer/controllers/address-lookup.js
- apps/new-dealer/fields/index.js
- apps/new-dealer/index.js
- apps/new-dealer/translations/src/en/fields.json
- apps/new-dealer/translations/src/en/pages.json
- apps/new-dealer/translations/src/en/validation.json
- apps/new-dealer/views/partials/postcode-manual-link.html
- codecept.conf.js
* Aded step to routes config,
* Added fields to field config,
* Added translations for pages, fields and validation,
* Added partial for the toggled field on step,
* Added acceptance tests,
* Added page helpers for the tests.
* fixed issue with addresses still being set in the sessionModel after it was used for previous postcode lookup
> flho-173 contact address for authority holders

- apps/new-dealer/acceptance/features/contact-address-authority-holder.js
- apps/new-dealer/acceptance/features/contact-address.js
- apps/new-dealer/acceptance/pages/contact-address.js
- apps/new-dealer/fields/index.js
- apps/new-dealer/index.js
- apps/new-dealer/translations/src/en/fields.json
- apps/new-dealer/translations/src/en/pages.json
- apps/new-dealer/translations/src/en/validation.json
Added the contact address step non authority holders. Consists of the postcode, manual-address and address-lookup steps.
* Added the steps to the route config,
* Added the translations for the pages, fields and validation,
* Added the acceptance tests for the steps.
> flho-152 contact-address

- apps/new-dealer/index.js
The testers are trying to test the end of the form but as soon as they click continue and end up on the smmary page, all the session data is cleared and they have to start the form again instead of being able to click back. 
So added `clearSession: false` to the summary step in the routes config to aid them.
> Added clearSession: false to the summary step

- apps/new-dealer/acceptance/features/authority-number-renew-vary.js
- apps/new-dealer/acceptance/pages/authority-holder-renew-vary.js
- apps/new-dealer/acceptance/pages/expiration-renew-vary.js
- apps/new-dealer/fields/index.js
- apps/new-dealer/index.js
- apps/new-dealer/translations/src/en/fields.json
- apps/new-dealer/translations/src/en/pages.json
- apps/new-dealer/translations/src/en/validation.json
- apps/new-dealer/views/authority-number-renew-vary.html
- assets/scss/app.scss
- codecept.conf.js
Added the authority-number-renew-vary step:
- Added the step to the routes config,
- Added the fields to the fields config,
- Added the custom html template,
- Added the translations for the page, fields and validation,
- Added the acceptance tests for the step and the page object,
- Changed the css class on the activity template and app.scss so it can be re-used for all summary-details sections
> flho-178 authority-number-renew-vary step

- apps/new-dealer/acceptance/features/storage-address.js
- apps/new-dealer/acceptance/pages/storage-add-another-address.js
- apps/new-dealer/acceptance/pages/storage-address.js
- apps/new-dealer/controllers/address-lookup.js
- apps/new-dealer/controllers/postcode.js
- apps/new-dealer/controllers/storage-add-another-address.js
- apps/new-dealer/controllers/storage-address-lookup.js
- apps/new-dealer/controllers/storage-address.js
- apps/new-dealer/controllers/storage-postcode.js
- apps/new-dealer/fields/index.js
- apps/new-dealer/index.js
- apps/new-dealer/translations/src/en/fields.json
- apps/new-dealer/translations/src/en/pages.json
- apps/new-dealer/translations/src/en/validation.json
- apps/new-dealer/views/partials/storage-address-summary.html
- apps/new-dealer/views/storage-add-another-address.html
- apps/new-dealer/views/storage-address-lookup.html
- apps/new-dealer/views/storage-address.html
- apps/new-dealer/views/storage-postcode.html
- assets/scss/app.scss
- codecept.conf.js
This step is to allow the user to add multiple addresses whilst using the same steps to loop over.
What is basically happening is, when we get to the address-lookup step or manual-address step, we are adding the address to an array along with an id and then clearing the fields in order to go around again.
When the user has added an address, the address will appear on the add-another-address step where they are able to change the address, add more or continue.
If the user chooses to add another address, they are taken to the storage-postcode step where they can do the process again. The user will be able to see the addresses the have added just like the add-another-address step. See prototype -> https://s5-firearms-application.herokuapp.com/apply/storage-address-add
If the user chooses to …
> flho-163 storage-add-another-address

- apps/new-dealer/acceptance/features/obtain.js
- apps/new-dealer/acceptance/pages/obtain.js
- apps/new-dealer/fields/index.js
- apps/new-dealer/index.js
- apps/new-dealer/translations/src/en/fields.json
- apps/new-dealer/translations/src/en/validation.json
- apps/new-dealer/views/partials/obtain-buy.html
* Removed toggled text boxes for buy, temp-possession and wont-be-in-possession options,
* Moved option acquire through other means to the bottom of the options,
* Removed toggled fields from fields config and route config,
* Removed translations for fields
* Removed some tests that aren't needed any more
> flho-297 Changes to the obtain step.

- apps/new-dealer/controllers/storage-address-lookup.js
For both locals and saveValues is there isn't a storage-postcode set in sessionModel then get the postcode from the storageAddresses using the id set in the req params.
Fixes bug where if you edit the postcode, the previous postcode was displaying.
Fixes bug where if you go to add-another-address, click back, click continue then click back again, the postcode does not display.
> fixed 2 bugs with the storage add another address step.

- apps/new-dealer/acceptance/features/company-name.js
- apps/new-dealer/acceptance/pages/company-name.js
- apps/new-dealer/controllers/confirm.js
- apps/new-dealer/fields/index.js
- apps/new-dealer/index.js
- apps/new-dealer/translations/src/en/fields.json
- apps/new-dealer/translations/src/en/pages.json
- apps/new-dealer/translations/src/en/validation.json
- apps/new-dealer/views/email/formatted.html
- apps/new-dealer/views/email/raw.html
- config.js
- docker-compose.yml
* On the organisation step, changed the field other-specify to other-name as the email will show the organisation name,
* Changed the acceptance tests to reflect this change,
* In the confirm controller: 
- Moved the getting of the contact name into it's own function. 
- Added a getEmailConfig function. This gets some data (organisation name, contact name, reference number) and adds it to the config. 
- Adjust the intro text to greet the contact holder and use the contact's name.
* Change the confirm route config to send email to the contact's email address,
* Added the email text to the pages translations file,
* Created two email templates raw and formatted,
* Adjusted the config to send email,
* Added env variables to the docker-compose file
> flho-338 Added the customer confirmation email

- apps/common/controllers/address-lookup.js
- apps/new-dealer/fields/index.js
- apps/new-dealer/translations/src/en/fields.json
Fix bug where **if** the address-lookup select step is used instead of manual, the `Change` link on the confirm step would take the user to the incorrect step. 
Previously when selecting the address on the lookup we were also setting the manual address with that address and using the manual address field on the confirm step. However this was causing an error with the Change link and the correct step was not being added to the link. 
Now we do not set the manual address in the session and instead display the address-lookup.
Added summary translations for all the address-lookup fields and removed `includeInSummary: false` from each address-lookup field in the config.
> Address-lookup Change link on Confirm page bug

- package.json
jscs is considered to be deprecated in favour of eslint.
> Remove jscs task

- .drone.yml
- .travis.yml
- package.json
The previous setup meant that the lang files were compiled when files changed, but did not trigger a restart of the server, so it would have to be restarted manually in order to see text changes. By including the lang file compilation in the main app start-up we can ensure that the running app in dev mode always shows the most recent content.
This does cause a slight overhead for restarts due to regular code changes, but it is minimal.
> Ensure translations are updated in dev mode when lang files change

- package.json
The sass compilation is performed on the docker container after an `npm i --production` and so needs to be a prod dependency.
> Move npm-sass to a prod dependency

- apps/common/controllers/loop.js
Only add a new record if there is at least one value. Prevents a bug manifestation that had empty addresses on an address loop.
> Prevent adding empty sets to looped fields

- apps/museums/controllers/exhibit-address-loop.js
- apps/museums/index.js
The address IDs were not being exposed to the client so it could not build the URLs correctly. Also the routing was not configured to recognise the parameters.
> FLHO-474 Allow museum addresses to be deleted

- .drone.yml
- .travis.yml
Automated tests can't run with CSP enabled so the app that runs for acceptance testing needs to have an envvar that turns it off.
> Disable CSP in the acceptance test runs

- package.json
`funkie` needs an explicit bump because it won't get patch updates at 0.0.x
`so-acceptance` gets an explicit bump because the previous version was fully broken.
> Bump versions of acceptance testing dependencies

- apps/new-dealer/index.js
The new template mixins means that declaring these fields causes them to be rendered as default, but they don't exist anywhere in field config or translations, and are not dependents of other fields.
> Remove non-existent fields from step config

- apps/new-dealer/acceptance/features/_happy-path.js
- apps/new-dealer/index.js
- package.json
Crude solution is to rename the step so it appears as two different steps rather than the same step in two places.
Adds an end-to-end test that passes through this journey.
> Fix bug with supporting docs pre-loop step blocking itself

- apps/common/behaviours/casework-submission.js
- apps/common/models/i-casework.js
- config.js
- package.json
Provides a behaviour that makes a POST to iCasework's create case API as part of `saveValues`. The behaviour allows for a custom `prepare` method to be passed as part of the behaviour configuration which can extend the default auth attributes with the appropriate case data for each of our applications.
```js
// in steps config
const CaseWorkSubmission = require('../common/behaviours/casework-submission');
'/confirm': {
behaviours: [
'complete',
CaseWorkSubmission({
prepare: (session) => { /* return data fields */ }
})
],
next: '/confirmation'
...
}
```
> Add behaviour for submission to iCasework

- apps/common/controllers/address-lookup.js
- apps/common/controllers/address.js
- apps/new-dealer/controllers/confirm.js
- apps/new-dealer/fields/index.js
If the user goes along multiple different forking paths in the same application then they end up with multiple addresses on their model, which end up being displayed multiple times.
Instead, if a user enters an address or fills a field in one place that makes a previous entry redundant then unset the old value.
> Unset multiple addresses

- apps/new-dealer/controllers/confirm.js
If a user selects "Other" for the usage question then the "additional details" they provide should also be shown on the confirm page alongside the selected options.
https://jira.digital.homeoffice.gov.uk/browse/FLHO-505
> Add "other usage" details to S5 confirm page

- apps/shooting-clubs/translations/src/en/validation.json
Because field names for manual address entry and dynamic lookup are the same the format for error message configuration needs to be changed to reflect this.
> Fix address error messaging for shooting clubs

- apps/common/behaviours/emailer.js
- package.json
Ensure that the timezone of the dates sent in outbound emails is in the UK timezone, irrespective of the timezone settings on the server itself.
> Fix timezone settings in live environments

- apps/common/views/error.html
Default template doesn't correctly use the startLink which is set by the error handler middleware so always redirects to root, which 404s dumping the user in a broken place.
> Override default error template

- apps/shooting-clubs/translations/src/en/validation.json
Old messages had "club secretary" where they should have read "second person".
> Fix validation messages for shooting clubs second contact

- Dockerfile
- run.sh
Added lots of comments about this.
We use run.sh for kubernetes and it's volume mounting.
/public starts as an empty dir so we copy the contents of /app/public
into /public for nginx to serve.
> Update docker file to use run.sh

- apps/new-dealer/fields/index.js
- apps/new-dealer/views/content/upload-documents-later.md
- apps/new-dealer/views/supporting-documents-add.html
Content explaining that an application may be delayed if no documents are uploaded needs to appear on selecting "upload later"
> Add expanding content to S5 upload later radio button

- docker-compose.yml
Set the nginx proxy versions for local development to be as per https://github.com/UKHomeOffice/kube-firearms/blob/master/kube/app-deployment.yml
> Use the same nginx proxy docker images as prod

- apps/new-dealer/controllers/confirm.js
If no documents are uploaded then `data['supporting-docs']` doesn't exist and so `map`-ing it fails.
> Fix error thrown on S5 confirm page if no supporting docs

- apps/new-dealer/fields/index.js
When changing the nominated contact from 1st auth holder to 2nd auth holder (for example) then clear any pre-entered contact details that might exist.
https://jira.digital.homeoffice.gov.uk/browse/FLHO-261
> Clear contact details when changing nominated contact

- apps/common/controllers/address/postcode.js
Previously the address lookup skipped back to the confirm answers page when submitting a postcode
https://jira.digital.homeoffice.gov.uk/browse/FLHO-500
> Allow address lookups to complete when editing

- apps/common/views/partials/add-another-address-summary.html
This was pulling the heading from the "/storage" page before so was showing "Will the prohibited items be stored on the business's premises in the UK?" which is patent nonsense.
> Fix heading for storage address summary table

- apps/new-dealer/fields/index.js
There was a section being shown on summary page which contained only the "do you want to add mroe addresses question". This was separate from the general storage address section.
> Hide s5 stoarge address loop question from summary

- config.js
This will set the max file upload size to 100mb in the app. It does not restrict the file size permitted by Nginx.
> Make the max file upload size 100mb

- apps/new-dealer/index.js
These will now appear in the business details section.
> Add existing authority details to S5 summary page

- apps/new-dealer/fields/index.js
The user needs to be able to fill in more than one country of origin, or be able to provide other free-form notes.
> Remove typeahead functionality from import field

- apps/new-dealer/controllers/confirm.js
- apps/new-dealer/fields/index.js
- apps/new-dealer/index.js
- package.json
This is really @easternbloc PR, details below:
This now takes into account the 8 possible address values that could be available
2 for each possible named person (manual,lookup) = 4
2 for authority-holder-contact-address (manual,lookup) = 2
2 for contact-address (Someone Else) (manual,lookup) = 2
Previous to this we were overwriting use-different-address in the confirm which was nasty so now we just add a new field to the section which we populate with the correct address data.
Updated hof-controllers to accommodate a bug in the confirm page for the edit link
> Updated logic for contact details in the confirm page

- apps/shooting-clubs/index.js
Because the address fields do not appear directly in the step configuration the automated step lookup for those fields does not resolve to a step and they need to be specified manually.
> Specify steps for address editing on shooting clubs confirm page

- apps/common/behaviours/casework-submission.js
In some circumstances icasework submission fails, but returns a 200 with an empty response. In these cases the line which accesses `data.createcaseresponse.caseid` fails because the JSON response is empty. By moving the call to next into a catch rather than a second argument we can ensure that these errors are caught and the request pipeline is not broken.
> Handle icasework failing with 200

- app.js
- package.json
It is now included in bootstrap so there's no need to include it here as well.
> Remove markdown middleware

- apps/common/controllers/address-lookup-loop.js
- apps/new-dealer/index.js
- apps/new-dealer/translations/src/en/pages.json
- apps/new-dealer/views/content/storage-addresses.md
- apps/new-dealer/views/storage-address-lookup.html
- apps/new-dealer/views/storage-address-manual.html
- apps/new-dealer/views/storage-address.html
- package.json
Adds an extra paragraph to the intro section on storage address pages.
This needed a bit of a template dance because the intro was stuck to being a single string, and couldn't handle the extra paragraph easily.
See https://github.com/UKHomeOfficeForms/hof-template-partials/pull/25
> Storage address intro

- apps/new-dealer/translations/src/en/validation.json
Add an error message for `required` validation on the supporting document add page
> Supporting document add error message

- app.js
- apps/common/behaviours/casework-submission.js
- apps/common/controllers/postcode.js
- package.json
This will hopefully allow us to get some more information about why casework submission might be failing in certain circumstances.
Module version updates courtesy of npm@5's auto `--save`, but no harm in updating things.
> Add debugging information to casework submission

- apps/shooting-clubs/translations/src/en/pages.json
Use the secretary's name instead of "the club secretary".
Use the contact's name instead of "the second person".
> Change shooting club contact labels

- apps/common/models/pdf.js
- package.json
so we can see exactly what the response is from the
HTML-PDF-converter when desired.
> Debug the response from HTML-PDF-converter

- assets/scss/app.scss
- package-lock.json
- package.json
* Previously by default all fields had a form-label-bold class by default.  The custom css was used to remove the bold.  This is no longer required because the latest hof-template-mixins fixes this issue
* The form-label-bold can now also be used for it's intended purpose
> Remove form-label-bold class from the custom css

- apps/common/behaviours/casework-submission.js
- apps/common/models/i-casework-documents.js
- apps/common/models/i-casework-getcase.js
- apps/common/models/i-casework.js
- apps/supporting-documents/behaviours/check-email.js
- apps/supporting-documents/behaviours/get-case.js
- apps/supporting-documents/emails/confirm.html
- apps/supporting-documents/fields/index.js
- apps/supporting-documents/index.js
- apps/supporting-documents/models/submission.js
- apps/supporting-documents/translations/src/en/fields.json
- apps/supporting-documents/translations/src/en/pages.json
- apps/supporting-documents/translations/src/en/validation.json
- config.js
- package.json
* Adds an email step to collect the email address associated with the original application.
* Performs a lookup of the case data from icasework to validate the email address
* Adds the documents to the case in icasework
* Sends an email to the original email address if successful
Note: this will need a config change on kube-firearms to update the icasework url to remove the path.
> Integrate the supporting docs app with icasework APIs

- apps/common/views/pdf.html
* Removes edit buttons
* Adds padding and border to table rows
* Preserves line breaks in content
I was looking at https://jira.digital.homeoffice.gov.uk/browse/FLHO-482 which seems to be not a bug, but while the data was all there, the formatting was a bit off. This makes it a bit better.
> Improve layout of pdf documents

- apps/supporting-documents/fields/index.js
- apps/supporting-documents/index.js
In supporting documents app, if a user goes back from the check answers page and edits the reference number then the original email should be re-entered to check it corresponds to that associated with the original application.
> Unset email when amending reference number

- apps/common/models/file-upload.js
If an error was returned from keycloak auth then the promise was being rejected but execution was allowed to continue. This caused the code immediately below to error and cause a crash as `response` is undefined in an error case.
Add the missing `return` statement to prevent this.
> Prevent further execution on upload auth error

- apps/common/controllers/supporting-documents.js
- apps/common/translations/src/en/buttons.json
- apps/common/translations/src/en/pages.json
- apps/common/views/supporting-documents.html
If a user has previously uploaded documents, and selects "Yes" to upload more documents then allow them to cancel and continue with their journey without adding more documents.
Do this by marking the upload step as complete on `get` if there are documents on the session. This allows the user to go directly to the next step without completing the form.
> Allow users to cancel out of an upload journey

- apps/new-dealer/controllers/confirm.js
If there are no supporting documents, but the array is present due to there previously having been documents (which were then deleted) then the supporting documents section of the check answers page should not be rendered.
> Check for empty supporting docs on S5 confirm page

- apps/common/behaviours/casework-submission.js
- package.json
icasework don't send anything useful in the response body for submission failures, so instead log the custom header they use for error messaging.
> Log error header on icasework failure

- apps/new-dealer/models/submission.js
- test/new-dealer/models/submission.test.js
The authority type parameter should be set according to the business activity of the applicant. Depending on the usage of the weapons they authirty will be classified as a dealer, carrier, dealer/carrier, or maritime guards.
> Set `AuthorityType` parameter on S5 iCasework submission

- apps/shooting-clubs/translations/src/en/pages.json
All variables are HTML escaped by default. This will return unescaped HTML to resolve the issue of apostrophes not displaying properly or any other such ASCII characters
Strangely the headers don't need the triple braces
https://jira.digital.homeoffice.gov.uk/browse/FLHO-704
> Add triple braces for values being passed in translations e.g {{{values.club-secretary-name}}}

- Dockerfile
bzip2 is required to successfully install phantomjs because if a binary is not found locally it downloads and unzips one.
> Install bzip2 on docker build

- apps/common/models/i-casework.js
- docker-compose.yml
We noticed when uploading large forms we'd hit the uri length limit in apache to icasework.
Doing it the right way using a proper payload fixes the issue now it's supported in their API
> Use JSON for icasework createcase

- apps/common/models/i-casework.js
Turns out these don't need to be query params they can also go in the body of the request.
This also fixes get-case and so supporting docs.
OOps!
> Moving params from prepare broke get-case

- apps/new-dealer/models/submission.js
- test/new-dealer/models/submission.test.js
Because `usage` can be either an array or a string this amend concats `usage` to an array, so that `filter()` can be invoked
This was throwing unhandled errors and causing the app not to respond
> Coerce `usage` to an array before filter

- apps/common/models/i-casework.js
- apps/supporting-documents/behaviours/get-case.js
- config.js
Failures of IP whitelisting with icasework manifest with a long pause (request takes ~120s) followed by an nginx "bad gateway" error due to it hitting its default timeout.
By setting an explicit timeout on our calls to icasework we can send a timeout error page before nginx fails, and so prevent the nginx error page from displaying.
Additionally we prevent catching the error when calling `getcasedetails` and so allow the app to fail early - rather than allowing the user to continue and then displaying an incorrect credentials error later. Since the timeout error is not related to sending a good or bad reference this does not represent a security issue.
> Throw timeout errors when calling icasework apis

- .gitignore
- package.json
- Upgrade hof-build to 1.6.0 to use the .env file 
- gitignore .env output/
> Upgrade hof build & gitignore

- apps/new-dealer/acceptance/features/session-error.js
- package.json
On a session timeout, ensure the "Start again" link returns users to the correct URL
https://jira.digital.homeoffice.gov.uk/browse/FLHO-724
> [FLHO-724] - Fix session timeout link

- app.js
A change so that the cookie banner reflects which service the user is on.
The cookie banner was showing the incorrect service title for the museums and shooting-clubs route
update to app.js to set the service name depending on the route
> SD-855 update cookie banner to reflect service

- app.js
An update to show the correct service name for each of the services when viewing the /cookies page
When accessing the cookies page the banner was incorrectly showing just the servicename for Prohibited weapons and ammunition licensing instead of the relevant service
updated app.js to initially set the servicename for the appropriate service and then perpetuate this throughout the form.
Tested locally
> SD-996 incorrect servicename on cookie banner

- package-lock.json
- package.json
What?
Security vulnerability in trim-newlines
Why?
Trim-newlines is a child dependency of a package that is no longer maintained
How?
Swapped out old package (npm-sass) for currently maintained equivalent (dart-sass) within hof-build
Testing?
Have done manual testing - No issues found.
N/A
Anything Else?
N/A
> Updated hof-build to fix security vulnerability

- apps/common/controllers/base.js
- apps/common/fields/index.js
- apps/common/translations/src/en/fields.json
- apps/museums/index.js
- apps/museums/models/submission.js
- apps/new-dealer/index.js
- apps/new-dealer/models/submission.js
- apps/shooting-clubs/index.js
- apps/shooting-clubs/models/submission.js
- package.json
- test/common/controllers/base.test.js
**Changes**
* Added 'Vary' selection to shooting-clubs, new-dealer and museums index.js pages.
* Updated fields.json to include new option.
* Updated submission.js in shooting-clubs, new-dealer and museums logic for new option.
* Updated index.js in shooting-clubs, new-dealer and museums for new fork step which follows the same as 'renew'.
* Added additional unit tests for 'vary' in base.test.js
* Changed find in submission.js for shooting-clubs, new-dealer and museums
> FA-33: Added 'Vary' to the activity page for shooting-clubs, new-dealer and museums.

- apps/museums/translations/src/en/fields.json
- apps/new-dealer/translations/src/en/fields.json
- apps/shooting-clubs/translations/src/en/fields.json
- kube/file-vault/file-vault-deployment.yml
**Changes**	
Added missing label for invoice address for postcode lookup page.
- invoice-address-select label added to fields.js for all forms.
Support added for PDF files extensions for file-vault.
- file-vault-deployment.yml changed to include support for file extensions in upper and mixed case, via a file-vault update.
> FA-85 and 86: Missing label for invoice address for postcode lookup page and support for uppercase file extensions for document uploaders

- apps/common/views/partials/existing-authority-documents-guidance.html
- apps/common/views/partials/supporting-documents-guidance.html
- apps/new-dealer/views/partials/supporting-documents-evidence-type-guidance.html
- yarn.lock
- Remove underline from text present on s5 existing-authority page (renew and amend pages)
- Remove underline from text present on s5 apply for new authority page.
- Update packages
- Underlines almost universally indicates linked text, so removing the underline from the non-link text to avoid confusion.
- Updating packages to resolve security vulnerabilities.
- Removed the 'summary' class which contains underline text-decoration from text. Text remains blue to differentiate the text.
- updated packages and updated cve exceptions where relevant.
Tested locally
> Firearms-98: remove underline from text present on s5 existing-authority page

- apps/common/views/partials/existing-authority-documents-guidance.html
- apps/common/views/partials/supporting-documents-guidance.html
- apps/new-dealer/views/partials/supporting-documents-evidence-type-guidance.html
reverted [Firearms-98](https://github.com/UKHomeOffice/firearms/pull/360/files) so that text is underlined once more.
To keep it inline with GDS component the text does need to be underlined.
tested locally
> revert firearms-98: add underline under text

- apps/common/fields/index.js
- apps/common/index.js
- apps/common/translations/src/en/fields.json
- apps/common/translations/src/en/journey.json
- apps/common/translations/src/en/pages.json
- apps/common/translations/src/en/validation.json
- apps/common/views/choose.html
What?
No root page exists meaning locals fail to load. This results in a 500 error in production when you click Continue on the root privacy page. We have now added a root page with 4 options so the user can choose their journey.
Why?
This gives a better user experience and less likely to experience unwanted journeys.
How?
Added a choose-a-journey radio field and the appropriate forking.
Testing?
Tested manually.
Anything Else?
> Added new root page and relevant navigation

- apps/museums/fields/index.js
- apps/museums/translations/src/en/validation.json
- apps/new-dealer/fields/index.js
- apps/new-dealer/translations/src/en/validation.json
- apps/shooting-clubs/fields/index.js
- apps/shooting-clubs/translations/src/en/validation.json
What?
Lock down phone number fields to only +(0-9)
Why?
The phone number fields currently accept anything
How?
Added the phonenumber validation rule to each field
Testing?
Tested locally
Anything Else?
> Firearms-3 - Added phonenumber validation rules to all phone numbers

- apps/common/fields/index.js
- apps/museums/fields/index.js
- apps/new-dealer/fields/index.js
- apps/shooting-clubs/fields/index.js
- apps/supporting-documents/fields/index.js
What?
Currently most input-text fields allow unlimited data to be entered, this causes UI issues as well as risk of overloading database fields. We have added additional validation rules to prevent this.
Why?
It was causing UI issues and there's potential risk of database issues when storing the data
How?
Added the maxlength validation rule. Using 320 for email fields, 15000 for text area fields and 200 for everything else.
Testing?
Tested locally
Anything Else?
> Firearms 68 - Max length changes

- .snyk
- apps/museums/fields/index.js
- apps/new-dealer/fields/index.js
- apps/shooting-clubs/fields/index.js
- test/_features/firearms/museums.feature
- test/_features/firearms/new-dealer.feature
- test/_features/firearms/shooting-clubs.feature
What?
As per conversation with the business, to prevent possible over zealous international phone number validation introduced in a previous commit, we should allow phone number fields to be blank.
How?
Removed the required attribute from all phone number fields.
Testing?
Tested locally
Screenshots?
N/A
> FIREARMS-3 Removed required on all phone number fields

- .drone.yml
**Changes**
- NODE_ENV added for uat acceptance tests in drone.yaml file, to mitigate errors in acceptance test due to wrong environment
> FIREARMS-126: NODE_ENV changed for UAT acceptance tests

- README.md
- server.js
Add the following CSP rules to service config
imgSrc: [
'www.google-analytics.com',
'ssl.gstatic.com',
'www.google.co.uk/ads/ga-audiences'
],
connectSrc: [
'https://www.google-analytics.com',
'https://region1.google-analytics.com',
'https://region1.analytics.google.com'
]
Support new GA analytics domain from https://region1.analytics.google.com to https://region1.google-analytics.com
> FIREARMS-112: add new CSP rules to service config

- .drone.yml
**What?**
 I've added Trivy Scanner to Pipeline and removed deprecated Anchore Scanner for the Firearms service, see ticket
[https://collaboration.homeoffice.gov.uk/jira/browse/HOFF-602](url)
**Why?**
Trivy will let you scan images, file systems and repositories for any vulnerabilities and issues. It will detect CVEs of OS packages, applications susceptibilities, and exposures of IaC in Terraform files, Kubernetes and Docker. Drawback of Anchore Scanner is it’s significantly slower, the process of using it is more cumbersome, the output is less friendly and most importantly, it scans fewer CVEs. 
**How?**
 Removed Anchore cve exception file and added trivy cve exception file in hof-services-config repo from Firearms configs. Removed Anchore Scanner steps from pipeline and added trivy …
> WIP -DO NOT MERGE - HOFF-602: Replace Anchore with Trivy

- .snyk
- bin/deploy.sh
Testers require Internal Ingress for automation testing. UAT Environment of Firearms never had Internal Ingress. We are deploying internal ingress . We are not allowing public access to any of the URLs. We also need to set Ingress class to nginx-internal. 
https://collaboration.homeoffice.gov.uk/jira/browse/HOFF-794
External ingress is returning 403 Forbidden error. 
Update if condition to Ingress annotations which are exported to internal ingress file in firearms repo
We can test by deploying to UAT. If we dont have admission policy in the namespace we will see the Drone build complaining about it while deploying to UAT
> HOFF-794: Deploy Internal Ingress for performance testing

- .snyk
- bin/deploy.sh
* Add the missing Internal Ingress 
* Add the Network Policies for Internal Ingress
* We are deploying Internal ingress for the first time for testers.
* We added Internal ingress annotations in hof-services-config
* Internal ingress is used by Testers as it can be accessed via kube_vpn 
* Testers will use this Internal ingress currently and in future to run automated tests (performance Tests)
* deploy scripts deploy the kubernetes objects to namespace
* We are now deploying internal ingress and network policies with these scripts to UAT env
> HOFF-794: Add internal ingress and network Policy

- apps/common/views/confirmation.html
- apps/museums/index.js
- apps/new-dealer/index.js
- apps/shooting-clubs/index.js
- config.js
- server.js
- Update link to feedback form - [FIREARMS-204](https://collaboration.homeoffice.gov.uk/jira/browse/FIREARMS-204)
- per business request to allow users to complete the latest version of the feedback form
- replaced old feedback link configuration in config.js and server.js with new feedbackUrl to be set with FEEDBACK_URL env picked from hof-services-config
- removed survey-url locals from index.js of different journeys as this has been replaced by one feedback url set in server.js
- updated link in confirmation.html to use new feedbackUrl from locals set in server.js
tested locally
> FIREARMS-204: Update link to feedback form

- apps/common/index.js
- apps/museums/index.js
- apps/new-dealer/index.js
- apps/shooting-clubs/index.js
- apps/supporting-documents/index.js
- package.json
- server.js
- yarn.lock
Update HOF framework version to v22.2.2 in Firearms licensing.
So that this form has access to the session timeout warning dialogue; by having this component, this form will increase its compliancy with WCAG 2.2
* Update hof version to 22.2.2 in package.json
* Add /session-timeout in apps/common/index.js
* Add /exit routes in apps/common/index.js, apps/museums/index.js, apps/new-dealer/index.js, apps/shooting-clubs/index.js, apps/supporting-documents/index.js
* Update yarn.lock
* Add session-timeout-warning behaviour to hof.settings.json
> FIREARMS-210: Update HOF framework version to v22.2.2
