UKHomeOffice/firearms

README.md, app.js, apps/new-dealer/fields/index.js, apps/new-dealer/index.js, package.json
- clones hof-boilerplate
- amends readme, package.json
- create dumy field
- create dummy route and steps
- update outdated dependencies
=> Build a skeleton app for the Firearms service

Dockerfile, docker-compose.yml, run.sh
- add Dockerfile
- add docker-compose.yml
- add run.sh
=> Add Docker configuration so the service can be run in a Docker container

app.js, apps/new-dealer/acceptance/features/company-name.js, apps/new-dealer/acceptance/pages/company-name.js, apps/new-dealer/fields/index.js, apps/new-dealer/index.js, apps/new-dealer/translations/src/en/fields.json, apps/new-dealer/translations/src/en/pages.json, apps/new-dealer/translations/src/en/validation.json, apps/new-dealer/views/partials/company.html, codecept.conf.js
Added company-name step:	
* Added step to routes config,
* Added fields to field config with toggle fields,
* Added translations for fields, pages and validation
* Added acceptance tests for the step,
* Added page helper for the tests
=> flho-142 Company-name step

apps/new-dealer/acceptance/features/obtain.js, apps/new-dealer/acceptance/pages/obtain.js, apps/new-dealer/acceptance/pages/storage.js, apps/new-dealer/fields/index.js, apps/new-dealer/index.js, apps/new-dealer/translations/src/en/fields.json, apps/new-dealer/translations/src/en/pages.json, apps/new-dealer/translations/src/en/validation.json, apps/new-dealer/views/partials/obtain-buy.html, assets/scss/app.scss, codecept.conf.js, package.json
* Added the step to the routes config,
* Added the translations to the fields pages and validation files. This includes deepTranslations,
* Added a template partial for the buy checkbox toggle,
* Added a line of sass for the partial removing a bottom margin,
* Added the acceptance tests for the obtain step,
* Added the page helper for obtain and storage,
* Added the helpers to the codecept config file.
=> Feature/flho146 obtain Step

apps/new-dealer/acceptance/features/storage.js, apps/new-dealer/acceptance/pages/storage.js, apps/new-dealer/acceptance/pages/usage.js, apps/new-dealer/fields/index.js, apps/new-dealer/index.js, apps/new-dealer/translations/src/en/fields.json, apps/new-dealer/translations/src/en/pages.json, apps/new-dealer/translations/src/en/validation.json, codecept.conf.js, test.sh
* Added the step to the routes config,
* Added the translations for the page, field and validation,
* Added the acceptance steps for the step
* Added the storage page step definition
=> flho-147 Added the storage step.

apps/new-dealer/acceptance/features/usage.js, apps/new-dealer/acceptance/pages/supporting-docs.js, apps/new-dealer/acceptance/pages/usage.js, apps/new-dealer/fields/index.js, apps/new-dealer/index.js, apps/new-dealer/translations/src/en/fields.json, apps/new-dealer/translations/src/en/pages.json, apps/new-dealer/translations/src/en/validation.json, codecept.conf.js
* Added the step to the routes config,
* Added the transaltions for pages, fields and validation which includes deepTranslations,
* Added the acceptance tests for the step,
* Added the page helper for the tests,
* Added supporting-docs page helper for the next step,
* Add supporting-docs helper to codecept config.
=> flho-148 Usage Step.

apps/new-dealer/acceptance/features/weapons.js, apps/new-dealer/acceptance/pages/ammunition.js, apps/new-dealer/acceptance/pages/authority-holders.js, apps/new-dealer/acceptance/pages/weapons.js, apps/new-dealer/fields/index.js, apps/new-dealer/index.js, apps/new-dealer/translations/src/en/fields.json, apps/new-dealer/translations/src/en/pages.json, apps/new-dealer/translations/src/en/validation.json, apps/new-dealer/views/partials/details-summary.html, apps/new-dealer/views/partials/weapons-unspecified.html, codecept.conf.js
* Added step to routes config with forking. When weapons and ammunition is selected on handle the next step is ammunition otherwise its authority holders,
* Added fields to the fields config which includes toggled fields
* Added transaltions for the page, fields and validation,
* Added template partials for details-summary on toggled fields and for unspecified weapon,
* Added acceptance tests for the step.
* Added page helper for step and also for ammunition and authority holders step,
* Added page helpers to codecept config.
=> flho-167 Weapons step.

apps/new-dealer/acceptance/features/authority-holders.js, apps/new-dealer/acceptance/pages/authority-holders.js, apps/new-dealer/acceptance/pages/first-authority-holders-name.js, apps/new-dealer/fields/index.js, apps/new-dealer/index.js, apps/new-dealer/translations/src/en/fields.json, apps/new-dealer/translations/src/en/pages.json, apps/new-dealer/translations/src/en/validation.json, codecept.conf.js
* Added tep to route config,
* Added radio-group field to fields config,
* Added translations for the page section, field and validation,
* Added acceptance tests for the step,
* Updated step helper with element ids,
* Created the page helper for the next step first-authority-holders-name
=> flho-169 Added the authority holders step:

apps/new-dealer/acceptance/features/first-authority-holders.birth.js, apps/new-dealer/acceptance/features/second-authority-holders-birth.js, apps/new-dealer/acceptance/pages/first-authority-holders-birth.js, apps/new-dealer/acceptance/pages/first-authority-holders-nationality.js, apps/new-dealer/acceptance/pages/second-authority-holders-birth.js, apps/new-dealer/acceptance/pages/second-authority-holders-nationality.js, apps/new-dealer/controllers/first-authority-holders-birth.js, apps/new-dealer/controllers/second-authority-holders-birth.js, apps/new-dealer/fields/index.js, apps/new-dealer/index.js, apps/new-dealer/translations/src/en/fields.json, apps/new-dealer/translations/src/en/pages.json, apps/new-dealer/translations/src/en/validation.json, apps/new-dealer/views/first-authority-holders-birth.html, apps/new-dealer/views/second-authority-holders-birth.html, codecept.conf.js
PR includes the steps for the first and second authority holders
* Added steps to the routes config,
* Added the controllers for the dob fields to the controllers directory,
* Added the custom html files to the views directory for the step,
* Added the translations for page, fields and validation,
* Added the acceptance tests for both steps,
* Edited the page helpers for the steps and added new ones for the next steps.
=> flho-171 birth details for first and second authority holders.

apps/new-dealer/acceptance/features/first-authority-holders-nationality.js, apps/new-dealer/acceptance/features/second-authority-holders-nationality.js, apps/new-dealer/acceptance/pages/first-authority-holders-address.js, apps/new-dealer/acceptance/pages/first-authority-holders-nationality.js, apps/new-dealer/acceptance/pages/second-authority-holders-address.js, apps/new-dealer/acceptance/pages/second-authority-holders-nationality.js, apps/new-dealer/controllers/authority-holders-nationality.js, apps/new-dealer/fields/index.js, apps/new-dealer/index.js, apps/new-dealer/translations/src/en/fields.json, apps/new-dealer/translations/src/en/pages.json, apps/new-dealer/translations/src/en/validation.json, apps/new-dealer/views/first-authority-holders-nationality.html, apps/new-dealer/views/partials/multi-nationality.html, apps/new-dealer/views/second-authority-holders-nationality.html, codecept.conf.js
authority holders nationality step for first and second authority holders
* Added step to routes config,
* Added custom controller for custom validation to ensure nationalities were not entered multiple times,
* Added fields to fields config,
* Added translations for fields, page and validation.
* Added custom templates for the steps
* Added acceptance tests for the steps and their page helpers.
=> flho-172 Authority holders nationality

apps/new-dealer/controllers/address-lookup.js
fixed bug with address lookup when running multiple instances. Options are mutated on GET but if a different instance is hit on POST the options are not set.
* added post hook to apply option adding logic
=> bugfix FLHO-233 - address lookup bug

apps/new-dealer/acceptance/features/storage-weapons-ammo.js, apps/new-dealer/acceptance/pages/storage-address.js, apps/new-dealer/acceptance/pages/storage-weapons-ammo.js, apps/new-dealer/fields/index.js, apps/new-dealer/index.js, apps/new-dealer/translations/src/en/fields.json, apps/new-dealer/translations/src/en/pages.json, apps/new-dealer/translations/src/en/validation.json, codecept.conf.js
* Added the step to the routes config and added forking to the supporting docs step to get to this step,
* Added the translations for validation, pages and fields,
* Added acceptance tests for the step and its page helpers
=> flho-227 storage-weapons-ammo step

apps/new-dealer/acceptance/features/storage-address.js, apps/new-dealer/acceptance/pages/storage-add-another-address.js, apps/new-dealer/acceptance/pages/storage-address.js, apps/new-dealer/fields/index.js, apps/new-dealer/index.js, apps/new-dealer/translations/src/en/fields.json, apps/new-dealer/translations/src/en/pages.json, apps/new-dealer/translations/src/en/validation.json, codecept.conf.js
storage-address section which includes postcode, address lookup and manual address steps.
* Added the steps to the route config,
* Added the translations for fields, pages and validation
* Added the acceptance tests for the steps
=> flho-163 Storage-address section

apps/new-dealer/acceptance/features/contact-details.js, apps/new-dealer/acceptance/pages/contact-address.js, apps/new-dealer/acceptance/pages/contact-details.js, apps/new-dealer/fields/index.js, apps/new-dealer/index.js, apps/new-dealer/translations/src/en/fields.json, apps/new-dealer/translations/src/en/pages.json, apps/new-dealer/translations/src/en/validation.json, codecept.conf.js
* Added step to routes config,
* Added fields to fields config,
* Added translations for pages, fields and validation,
* Added acceptance tests for the step,
* Added the page helper for the acceptance tests.
=> flho-151 contact-details step

apps/new-dealer/acceptance/features/contact-address-authority-holder.js, apps/new-dealer/acceptance/pages/contact-address-authority-holder.js, apps/new-dealer/fields/index.js, apps/new-dealer/index.js, apps/new-dealer/translations/src/en/fields.json, apps/new-dealer/translations/src/en/validation.json
Added the manual address and address-lookup steps to the section.
* Added steps to the route config,
* Added fields to the fields config,
* Added the translations for the fields and the validation,
* Added the acceptance tests for the steps
Made some changes to the original step: url, field name and some changes to the tests and page helper
=> flho-173 authority holders contact address. 

apps/new-dealer/acceptance/features/activity.js, apps/new-dealer/acceptance/pages/activity.js, apps/new-dealer/acceptance/pages/authority-holder-renew-vary.js, apps/new-dealer/fields/index.js, apps/new-dealer/index.js, apps/new-dealer/translations/src/en/fields.json, apps/new-dealer/translations/src/en/pages.json, apps/new-dealer/translations/src/en/validation.json, apps/new-dealer/views/activity.html, assets/scss/app.scss, codecept.conf.js
Added the activity step to the form:	
* Added the step to the routes config,
* Added the field to the fields config,
* Added the translations to the pages, fields and validation
* Added custom template for the step
* Added a little css for the summary-details toggle,
* Added acceptance tests and page objects.
=> flho-159 activity Step.

apps/new-dealer/translations/src/en/pages.json
Changed the header content on the storage step
=> flho-299 Changed the header on the storage step

apps/new-dealer/acceptance/features/usage.js, apps/new-dealer/acceptance/pages/usage.js, apps/new-dealer/fields/index.js, apps/new-dealer/translations/src/en/fields.json, apps/new-dealer/translations/src/en/pages.json, apps/new-dealer/translations/src/en/validation.json
* Added deactivation option to the checkbox-group,
* Removed toggled textarea fields from the checkbox-group (except for other),
* Removed translations for the toggled fields,
* Removed toggled field tests from the acceptance tests
=> flho-303 usage step changes.

apps/new-dealer/acceptance/features/first-authority-holders-address.js, apps/new-dealer/acceptance/features/second-authority-holders-address.js, apps/new-dealer/acceptance/features/storage-address.js, apps/new-dealer/acceptance/features/storage.js, apps/new-dealer/acceptance/features/usage.js, apps/new-dealer/index.js
* Changed the order of the steps based on the changes to the prototype.
* Changed the acceptance tests to reflect the changes.
=> Step workflow Changes

apps/new-dealer/controllers/address-lookup.js, apps/new-dealer/controllers/authority-holders-nationality.js, apps/new-dealer/controllers/base.js, apps/new-dealer/controllers/contact.js, apps/new-dealer/controllers/postcode.js, apps/new-dealer/controllers/storage-add-another-address.js, apps/new-dealer/controllers/storage-address-lookup.js, apps/new-dealer/controllers/storage-address.js, apps/new-dealer/controllers/storage-postcode.js, apps/new-dealer/index.js, apps/new-dealer/models/postcodes.js, assets/js/index.js, assets/scss/app.scss, package.json
* left pointing at bootstrap#development while in development
* installed hof-frontend-toolkit
* installed eslint-config-homeoffice
* updated so-acceptance to v4
* updated refs to hof
=> Chore updated in line with so-master removal

apps/new-dealer/acceptance/features/confirmation.js, apps/new-dealer/acceptance/pages/confirmation.js, apps/new-dealer/controllers/confirmation.js, apps/new-dealer/index.js, apps/new-dealer/translations/src/en/pages.json, apps/new-dealer/views/confirmation.html, assets/scss/app.scss
* Added the step to the route config,
* Added custom html for page,
* Added translations for page,
* Added custom controller for translation logic for bullet points and for when the user selects arm-guards in the usage step,
* Added acceptance tests for the page.
=> flho-313 Added the confirmation page to the form.

apps/new-dealer/acceptance/features/confirm.js, apps/new-dealer/acceptance/pages/confirm.js, apps/new-dealer/fields/index.js, apps/new-dealer/index.js, apps/new-dealer/translations/src/en/fields.json, apps/new-dealer/views/confirm.html
* Removed the declaration checkbox.
* Changed tests to reflect this. 
* Add import field to summary page. 
* Change summary label for import country and obtain through other means fields
=> Confirm step fixes

apps/shooting-clubs/acceptance/features/club-secretary-address.js, apps/shooting-clubs/acceptance/features/club-secretary-name.js, apps/shooting-clubs/acceptance/pages/club-secretary-address.js, apps/shooting-clubs/acceptance/pages/club-secretary-email.js, apps/shooting-clubs/fields/index.js, apps/shooting-clubs/index.js, apps/shooting-clubs/translations/src/en/fields.json, apps/shooting-clubs/translations/src/en/pages.json, apps/shooting-clubs/translations/src/en/validation.json, codecept.conf.js
* Added the step to the routes config. 
* Added the fields to the fields config. 
* Added the translations for pages, fields and validation. 
* Added acceptance tests for the step
=> flho-344 club secretary address step.

apps/shooting-clubs/acceptance/features/club-secretary-email.js, apps/shooting-clubs/acceptance/features/club-secretary-name.js, apps/shooting-clubs/acceptance/pages/club-secretary-email.js, apps/shooting-clubs/fields/index.js, apps/shooting-clubs/index.js, apps/shooting-clubs/translations/src/en/fields.json, apps/shooting-clubs/translations/src/en/pages.json, apps/shooting-clubs/translations/src/en/validation.json
https://jira.digital.homeoffice.gov.uk/browse/FLHO-345
=> FLHO-345-shooting clubs: Adding the Club Secretary Email form page

apps/shooting-clubs/acceptance/features/second-contact-email.js, apps/shooting-clubs/acceptance/pages/location-postcode.js, apps/shooting-clubs/acceptance/pages/second-contact-email.js, apps/shooting-clubs/fields/index.js, apps/shooting-clubs/index.js, apps/shooting-clubs/translations/src/en/fields.json, apps/shooting-clubs/translations/src/en/pages.json, apps/shooting-clubs/translations/src/en/validation.json, codecept.conf.js
* Add the fields to the steps file & fields file
* Add the acceptance tests
* Add the translations
https://jira.digital.homeoffice.gov.uk/browse/FLHO-348
=> Second Contact Email page:

apps/shooting-clubs/translations/src/en/pages.json
=> Second contact name

.travis.yml, Dockerfile-acceptance, package.json, test.sh
Remove the need to manually orchestrate phantom by wrapping the test runner in the funkie library, which handles webdriver processes automatically.
Cleans up acceptance test invocation using new so-acceptance library.
=> Refactor acceptance test scripts

test/common/models/file-upload.test.js, test/new-dealer/controllers/supporting-documents.test.js
The property names changed in implementation and so need to also change in tests
=> Fix property names in supporting docs upload tests

apps/museums/controllers/contact-address-select.js, apps/museums/fields/index.js, apps/museums/index.js, apps/museums/translations/src/en/fields.json, apps/museums/translations/src/en/pages.json
Allows a user to select from a list of previously entered addresses to choose their contact address
=> Address selection step

apps/common/controllers/loop.js, apps/shooting-clubs/controllers/storage-address-loop.js, apps/shooting-clubs/controllers/storage-address.js, apps/shooting-clubs/index.js, apps/shooting-clubs/translations/src/en/fields.json, apps/shooting-clubs/translations/src/en/pages.json
Adds a new step after storage address selection to add more storage addresses if needed.
=> Additional storage addresses

.drone.yml, .travis.yml, apps/common/behaviours/casework-submission.js, apps/common/controllers/legacy-confirm.js, apps/common/controllers/supporting-documents.js, apps/common/models/file-upload.js, apps/common/models/i-casework.js, apps/common/translations/src/en/pages.json, apps/common/views/confirmation.html, apps/common/views/partials/confirmation-alert.html, apps/museums/acceptance/features/_happy-path.js, apps/museums/index.js, apps/museums/models/submission.js, apps/new-dealer/acceptance/features/_happy-path.js, apps/new-dealer/acceptance/features/confirm.js, apps/new-dealer/acceptance/features/confirmation.js, apps/new-dealer/controllers/confirm.js, apps/new-dealer/index.js, apps/new-dealer/models/submission.js, apps/new-dealer/views/confirmation.html, apps/shooting-clubs/acceptance/features/_happy-path.js, apps/shooting-clubs/index.js, apps/shooting-clubs/models/submission.js, apps/supporting-documents/views/confirmation.html, assets/scss/app.scss, codecept.conf.js, config.js, package.json, test/common/models/file-upload.test.js, test/new-dealer/controllers/supporting-documents.test.js
This needs testing end-to-end with file uploads and icasework, but this is a decent enough first candidate.
Each app has `apps/**/models/submission.js` which returns mapped fields for that app. Default stuff and auth is handled in `apps/common/models/i-casework.js`.
To test this, you'll need icasework auth params as environment variables. Hit me up for these.
=> Submission models

.drone.yml, Dockerfile, apps/common/behaviours/generate-pdf.js, package.json
Install and use a phantomjs
Add fonts for phantom
=> Update build pipeline to use node 6 and 7

apps/shooting-clubs/translations/src/en/pages.json
See https://jira.digital.homeoffice.gov.uk/browse/FLHO-504
=> Fix confirm page label

config.js
Reduce repetition in local urls. Stop caring what "no prod" environment is running.
=> Clean up config file environments

apps/museums/views/content/declaration.md, apps/new-dealer/views/content/declaration.md, apps/shooting-clubs/views/content/declaration.md
Per https://jira.digital.homeoffice.gov.uk/browse/FLHO-387
=> Add declaration content for apps

apps/museums/index.js, apps/museums/translations/src/en/fields.json, apps/museums/translations/src/en/pages.json
If a user selects a renewal then display an additional step to ask for the licence number
=> Add step for existing licence number

app.js, apps/common/controllers/supporting-documents.js, apps/common/models/file-upload.js, apps/common/translations/src/en/validation.json, config.js, package.json
Provides error messages for the user when uploading a file with either the wrong file type, or that is too large.
=> Add error handling for file upload

apps/museums/index.js, apps/new-dealer/index.js, apps/shooting-clubs/index.js
This has to happen off the confirm page for now.
=> Fix PDF generation.

apps/shooting-clubs/translations/src/en/pages.json
https://jira.digital.homeoffice.gov.uk/browse/FLHO-467
=> Update heading for shooting club address select step

apps/shooting-clubs/translations/src/en/validation.json
https://jira.digital.homeoffice.gov.uk/browse/FLHO-502
=> Add validation messages for "add another" address fields

apps/shooting-clubs/models/submission.js
This was crashing the app when you only add one address-category.
=> Only do a join if it's an array.

app.js, apps/shooting-clubs/views/content/declaration.md
Just a little copy to add to the declaration for shooting clubs
=> Add missing shooting club declaration copy

apps/shooting-clubs/fields/index.js, apps/shooting-clubs/index.js, apps/shooting-clubs/translations/src/en/fields.json, apps/shooting-clubs/translations/src/en/pages.json, apps/shooting-clubs/translations/src/en/validation.json
Shows for new authority applications and not for renewals
=> Add additional question step for new shooting club

apps/common/models/i-casework.js, apps/museums/models/submission.js, apps/new-dealer/models/submission.js, apps/shooting-clubs/models/submission.js
The values for these parameters have been re-defined by icasework. These are the new values.
=> Update AuthorityType and ApplicationType properties on submission

package.json
Fixes styling issues around header markup changes
=> Update toolkit version

package.json
This allows us to pass a redis password into the redis client
=> Update version of bootstrap.

apps/new-dealer/models/submission.js
Reverts UKHomeOffice/firearms#194
This makes iCaswork hang when we do a submission to it so the application process fails (502!)
=> Revert "Add organisation field to S5 casework submission"

apps/new-dealer/models/submission.js
Key in casework is now `Customer.Organisation` rather than simply `Organisation`.
=> Re-add organisation field

apps/common/translations/src/en/fields.json, apps/common/translations/src/en/validation.json, apps/new-dealer/translations/src/en/pages.json
=> Change the S5 'upload supporting document' content

apps/common/behaviours/pdf-upload.js, test/common/behaviours/pdf-upload.test.js
There will be a corresponding PR to kube-firearms to set the log level for dev to `debug` as well, so wait for that before merging this so it deploys that way.
=> Add debug logging to PDF creation and upload behaviour

apps/supporting-documents/translations/src/en/pages.json
Per https://jira.digital.homeoffice.gov.uk/browse/FLHO-692
=> Update supporting documents app content

apps/new-dealer/translations/src/en/validation.json
- validation messages when a user does not select a nationality not from the list.
=> Add validation messages for Authority Holder nationality

package.json
- Also adds the little arrow to the select box
=> Update hof-theme-govuk to get latest styles

apps/common/views/content/declaration.md, apps/museums/views/content/declaration.md, apps/shooting-clubs/views/content/declaration.md
- This is for all 3 apps- new dealer, shooting-clubs and museums
=> Add declaration content

.drone.yml, apps/museums/acceptance/features/_happy-path.js, apps/new-dealer/acceptance/features/_happy-path.js, apps/new-dealer/acceptance/features/ammunition.js, apps/new-dealer/acceptance/features/authority-holders.js, apps/new-dealer/acceptance/features/company-name.js, apps/new-dealer/acceptance/features/confirm.js, apps/new-dealer/acceptance/features/confirmation.js, apps/new-dealer/acceptance/features/contact-address-authority-holder.js, apps/new-dealer/acceptance/features/contact.js, apps/new-dealer/acceptance/features/first-authority-holders-nationality.js, apps/new-dealer/acceptance/features/handle.js, apps/new-dealer/acceptance/features/import.js, apps/new-dealer/acceptance/features/obtain.js, apps/new-dealer/acceptance/features/second-authority-holders-nationality.js, apps/new-dealer/acceptance/features/storage-address-edit.js, apps/new-dealer/acceptance/features/storage-address.js, apps/new-dealer/acceptance/features/storage.js, apps/new-dealer/acceptance/features/usage.js, apps/new-dealer/acceptance/features/weapons.js, apps/shooting-clubs/acceptance/features/_happy-path.js, apps/shooting-clubs/acceptance/features/activity.js, apps/shooting-clubs/acceptance/features/location-address.js, apps/supporting-documents/acceptance/features/_happy-path.js
Address the failures in a later commit
wait for selenium before test
=> Comment out failing acceptance tests for now.

apps/new-dealer/acceptance/features/first-authority-holders-nationality.js, apps/new-dealer/translations/src/en/validation.json
this is when a user does not select a country on a list for the second nationality and third nationality for the first authority holder's nationality
=> [FLHO-732] - error message for invalid nationality

apps/common/translations/src/en/pages.json, apps/common/views/content/declaration.md, apps/common/views/content/privacy.md, apps/common/views/privacy.html, apps/museums/index.js, apps/museums/views/content/declaration.md, apps/new-dealer/index.js, apps/shooting-clubs/index.js
These are the initial changes for GDPR on the s5 journey.
They include a new privacy page and the removal of content from the confirmation page
=> [HOF-1][HOF-2] GDPR Changes

package.json
Update so-acceptance to work with that
=> Update hof to use new encryption in the redis session.

README.md
Reverts UKHomeOffice/firearms#330
=> Revert "SD-924 alter readme to check filevault update"

README.md
-Change in README.md to check for changes to firewall in dev
=> SD-1001 Alter readme

apps/common/views/partials/existing-authority-documents-guidance.html, apps/common/views/partials/summary-table.html, apps/common/views/partials/supporting-documents-guidance.html, apps/new-dealer/views/partials/supporting-documents-evidence-type-guidance.html, assets/scss/app.scss, yarn.lock
Assign correct heading levels to heading (Note - this branch is created from [FIREARMS-98](https://github.com/UKHomeOffice/firearms/pull/360), so the first 6 commits belong to FIREARMS-98 and only the last commit pertains to this pull request)
Accessibility - Headings are coded with heading mark-up (`<h1>` - `<h6>`). Headings assigned the correct heading level h tags should be sequential
- Changed heading level tag from `<h3>` to `<h2>`
- Amended scss to update template
Tested locally
=> Firearms-100: assign correct heading levels to heading

apps/common/views/partials/existing-authority-documents-guidance.html, apps/common/views/partials/summary-table.html, apps/common/views/partials/supporting-documents-guidance.html, apps/museums/views/partials/multiple-fields-summary-table.html, apps/new-dealer/views/partials/multiple-fields-summary-table.html, apps/new-dealer/views/partials/supporting-documents-evidence-type-guidance.html, apps/shooting-clubs/views/partials/multiple-fields-summary-table.html, assets/scss/app.scss, yarn.lock
Resolved accessibility alert caused by underlined text(Note - this branch is created from [FIREARMS-100](https://github.com/UKHomeOffice/firearms/pull/367), so only the last commit pertains to this pull request).
The accessibility alert states that there is underlined non-linked text and suggests that underlines should indicate linked text. The text in this case is in fact linked text and should be underlined but the alert occurs because there is a css style underlining the `<span>` tag surrounding the `<a>` tag.
Moved css class from span tag to anchor tag. Css styling remains the same but no longer flags the accessibility alert.
Tested locally
=> Firearms 101: Underlined text present on the firearms forms s5/Museum/Shooting clubs confirm page 

apps/common/views/partials/existing-authority-documents-guidance.html, apps/common/views/partials/summary-table.html, apps/common/views/partials/supporting-documents-guidance.html, apps/museums/views/partials/multiple-fields-summary-table.html, apps/new-dealer/acceptance/features/first-authority-holders.birth.js, apps/new-dealer/acceptance/features/second-authority-holders-birth.js, apps/new-dealer/acceptance/pages/first-authority-holders-birth.js, apps/new-dealer/acceptance/pages/second-authority-holders-birth.js, apps/new-dealer/fields/index.js, apps/new-dealer/index.js, apps/new-dealer/views/first-authority-holders-birth.html, apps/new-dealer/views/partials/multiple-fields-summary-table.html, apps/new-dealer/views/partials/supporting-documents-evidence-type-guidance.html, apps/new-dealer/views/second-authority-holders-birth.html, apps/shooting-clubs/views/partials/multiple-fields-summary-table.html, assets/scss/app.scss, yarn.lock
- Add dropdown list for country of birth
- Amend acceptance tests to reflect country of birth pages
(Note - this branch is created from [FIREARMS-101](https://github.com/UKHomeOffice/firearms/pull/371) - only the last two commits pertain to this pull request).
The Country of Birth field doesn't have dropdown list where as other similar fields Country of Nationality and Second Nationality have drop down lists. 
- Changed input text field to dropdown list for first authority and second authority country of birth field.
Tested locally
=> firearms-57: add dropdown list for country of birth

apps/supporting-documents/behaviours/check-email.js, test/_features/firearms/supporting-documents.feature
What?
Current icasework ref check is failing due to a minor bug in the logic
Why?
The check was not comparing with the user input
How?
Added string comparison
Testing?
Tested locally and added additional acceptance test
Anything Else?
=> FIREARMS-113 Fixed issue with supporting doc ref check and added test

apps/new-dealer/fields/index.js, apps/new-dealer/translations/src/en/validation.json
What?
Validate DOB to ensure contact is over 18
Why?
Right now there is nothing in place to ensure the contact is of a valid age
How?
Added the over18 validation rule
Testing?
Tested locally
Anything Else?
=> FIREARMS-52 - Fixed validation issue

apps/shooting-clubs/models/submission.js
What?
Removed part of the summary code which appends storage locations into the shooting ranges before submission to icasework 
Why?
Storage locations are appearing in the Shooting Ranges section in icasework
How?
Removed the code causing this issue
Testing?
Tested locally
Anything Else?
=> FIREARMS-92 - Removed section of code causing the dups

.drone.yml, config.js
**Jira Ticket**
https://collaboration.homeoffice.gov.uk/jira/browse/FIREARMS-118
**Changes**
- Changed ICASEWORK_TIMEOUT to 60000 in config.js to mitigate timeout errors when sending to iCasework.
- Added branch name translation into acceptance test branch, to allow for branches named like the following "feature/Firearms-123".
- Tested on the branch environment end to end
=> FIREARMS-118: Changed ICASEWORK_TIMEOUT and acceptance test URL translation

apps/common/views/content/privacy.md
**Changes**
- Email and Telephone number changed in privacy.md
=> FIREARMS-126: Telephone number and email change for privacy page

apps/common/views/content/privacy.md
Reverts UKHomeOffice/firearms#415
=> Revert "FIREARMS-126: Telephone number and email change for privacy page"

config.js, package.json, server.js, yarn.lock
What?
The feedback link in the banner is no longer working
How?
We have ensured the url is set when the user starts their journey which the framework then renders out
Testing?
Tested locally
Screenshots?
N/A
=> FIREARMS-129 Fixed feedback URL

.snyk, apps/new-dealer/translations/src/en/pages.json, package.json, yarn.lock
FIREARMS-162 Modified text on S5 supporting docs as per discussion with the business.
=> FIREARMS-162 Changed text in the S5 Supporting Docs page

apps/supporting-documents/views/supporting-documents.html
Removed unrequired option from Supporting Documents journey
=> FIREARMS-133 Removed dont upload option

.snyk, kube/app/ingress-external.yml, kube/app/ingress-internal.yml
Updated ingress config due to breaking change
=> Updated ingress config due to breaking change

.drone.yml, .snyk, Dockerfile, Dockerfile-acceptance, apps/common/controllers/supporting-documents.js, apps/common/views/supporting-documents.html, apps/shooting-clubs/index.js, apps/shooting-clubs/models/submission.js, apps/shooting-clubs/sections/summary-data-sections, apps/shooting-clubs/translations/src/en/pages.json, apps/shooting-clubs/translations/src/en/validation.json, package.json, test/_features/firearms/shooting-clubs.feature
Added ability to upload supporting docs to Shooting Clubs as per request from the business.
=> FIREARMS-163 - Added supporting docs step to shooting clubs

.drone.yml
**Changes**
- Sonar scanner image changed to mitigate errors caused by previous image.
=> NRM-237: Sonar Scanner image changed

README.md
Test GA4 migration for firearms 
Make sure Firearms is being tracked in GA4
=> WIP FIREARMS-112 - GA4 Migration test

package.json, yarn.lock
[HOFF-635 ](https://collaboration.homeoffice.gov.uk/jira/browse/HOFF-635).- changing Queen's crown to King's crown logo
 
The Gov.uk crown logo changed
 
yarn add hof@20.4.0
 
Tested locally
 
 
=> HOFF-635 Update-Firearms-to-HOF-v20-4-0

.snyk, apps/common/views/accessibility.html, package.json, pull-request-template.md, pull-request.md, yarn.lock
Updated Accessibility Statement
As requested by product owner per ticket [HOFF 878](https://collaboration.homeoffice.gov.uk/jira/browse/HOFF-878)
Added a HTML file for the accessibility page
=> [HOFF-878] updated accessibility statement

.drone.yml
=> [HOFF-878] remove acceptance test uat

.snyk, apps/common/views/partials/add-another-address-summary.html, apps/museums/views/partials/add-another-address-summary.html, apps/new-dealer/views/partials/add-another-address-summary.html, apps/shooting-clubs/views/partials/add-another-address-summary.html, yarn.lock
reviving the work done by @PaolaDMadd-Pro to address this accessibility issue.  
- update partials view in the following files:
1. apps/new-dealer/views/partials/add-another-address-summary.htm
2. apps/museums/views/partials/add-another-address-summary.html
3. apps/common/views/partials/add-another-address-summary.html
4. apps/shooting-clubs/views/partials/add-another-address-summary.html
- update yarn.lock
https://collaboration.homeoffice.gov.uk/jira/browse/FIREARMS-201
app branch:  https://firearms-licensing-firearms-201-tableaccessibilityissue.internal.firearms-branch.homeoffice.gov.uk
=> FIREARMS-201: Layout table -Storage Add Another Address

.snyk, apps/common/views/partials/add-another-address-summary.html, apps/museums/views/partials/add-another-address-summary.html, apps/new-dealer/views/partials/add-another-address-summary.html, apps/shooting-clubs/views/partials/add-another-address-summary.html, yarn.lock
This reverts commit eab84f9664b62be81d5311909b3fe5881a580734.
Branch was merged before branch-testing.  
=> Revert "FIREARMS-201: Layout table -Storage Add Another Address (#517)"

apps/common/views/partials/add-another-address-summary.html, apps/museums/views/partials/add-another-address-summary.html, apps/new-dealer/views/partials/add-another-address-summary.html, apps/shooting-clubs/views/partials/add-another-address-summary.html, yarn.lock
reviving the work done by @PaolaDMadd-Pro to address this accessibility issue.  
- update partials view in the following files:
1. apps/new-dealer/views/partials/add-another-address-summary.htm
2. apps/museums/views/partials/add-another-address-summary.html
3. apps/common/views/partials/add-another-address-summary.html
4. apps/shooting-clubs/views/partials/add-another-address-summary.html
- updated yarn.lock
https://collaboration.homeoffice.gov.uk/jira/browse/FIREARMS-201
app branch:  https://firearms-licensing-firearms-201-tableaccessibilityissue.internal.firearms-branch.homeoffice.gov.uk
=> Firearms 201 table accessibility issue

.drone.yml, .snyk, apps/common/views/accessibility.html
1. Updating the accessibility statement to remove mention of table for layout.  
2. updated .snyk policy file
3. removed Acceptance Tests from pipeline
1. https://collaboration.homeoffice.gov.uk/jira/browse/FIREARMS-203
2. Snyk tests failing
3. Acceptance tests failing, and are redundant with other tests done.  
1. Removed the out-of-date lines from accessibility.html.  Updated the dates noted the page was reviewed and tested etc.  
2. updated snyk policy file
3. removed Acceptance tests from .drone.yml
app url:  https://firearms-licensing-firearms-203-accessibilitystatement.internal.firearms-branch.homeoffice.gov.uk
=> FIREARMS-203: Update Accessibility Statement

kube/html-pdf/html-pdf-deployment.yml
* Using html-pdf-converter image with Node v 22 and upgraded node packages
* Fixed vulnerabilities in the image
* Testing in Branch env
* Large number of Critical and High CVE Vulnerabilities have been detected by Trivy Scan
* Node image v18 is outdated. HOF is moving to v20 and v22 in future Goals.
* Replace html-pdf-converter image with latest
* Add a comment to explain the version and Date.
* Smoke tests done on firearms, received notification
* Regression testing in Branch and then merge to master to deploy and test in UAT, Stage and promote to Prod
* Check boxes will ticked as we pass through each env
* Drone build is successful
* Pods are Healthy
=> FIREARMS-209: Update html-pdf-converter image with latest v3.0.0

.drone.yml
[HOFF-1117](https://collaboration.homeoffice.gov.uk/jira/browse/HOFF-1117) git flow test
https://collaboration.homeoffice.gov.uk/pages/viewpage.action?pageId=371154882
https://collaboration.homeoffice.gov.uk/pages/viewpage.action?pageId=371154882
Newly introduced steps are working as intended
=> HOFF-1117 SPIKE DO NOT MERGE (WIP)

.drone.yml
[HOFF-1117](https://collaboration.homeoffice.gov.uk/jira/browse/HOFF-1117) git flow test
https://collaboration.homeoffice.gov.uk/pages/viewpage.action?pageId=371154882
https://collaboration.homeoffice.gov.uk/pages/viewpage.action?pageId=371154882
Newly introduced steps are working as intended
=> HOFF-1117 more changes

.drone.yml, apps/common/index.js, apps/museums/index.js, apps/new-dealer/index.js, apps/shooting-clubs/index.js, apps/supporting-documents/index.js, package.json, server.js, yarn.lock
[HOFF-1117](https://collaboration.homeoffice.gov.uk/jira/browse/HOFF-1117) git flow test
https://collaboration.homeoffice.gov.uk/pages/viewpage.action?pageId=371154882
https://collaboration.homeoffice.gov.uk/pages/viewpage.action?pageId=371154882
Newly introduced steps are working as intended
=> HOFF-1117 tagging into uat

.drone.yml
[HOFF-1117](https://collaboration.homeoffice.gov.uk/jira/browse/HOFF-1117) git flow test
https://collaboration.homeoffice.gov.uk/pages/viewpage.action?pageId=371154882
https://collaboration.homeoffice.gov.uk/pages/viewpage.action?pageId=371154882
Newly introduced steps are working as intended
=> HOFF-1117 spike test

.drone.yml
=> release-test

.drone.yml
=> trigger build on stg

.drone.yml
Test into stage
Git flow test
changing the pipeline
Manual
https://collaboration.homeoffice.gov.uk/pages/resumedraft.action?draftId=371155217&draftShareId=b58862b1-d829-4efb-87be-0630aa192752&## Anything Else? (optional)
=> indendation error

apps/common/views/accessibility.html
Updated Accessibility Statement. [FIREARMS-215](https://collaboration.homeoffice.gov.uk/jira/browse/FIREARMS-215)
As per business requirement.
Removed some statements and updated some words in the accessibility.html
Manual testing conducted to check the contents on accessibility page.
=> [FIREARMS-215] Updated Accessibility Statement.
